//  ===================================
// # MV Clouds Private Limited
// # Author: Nimit Shah
// # Create Date: 18/01/2023
// # Description: Used for Edit, Delete, Read or Create New Form
// # Change Version History
// # Version No.     Author          Date            Change Description            Jira Ticket
// #    1.           Nimit         18/01/2023           Home Page UI 		     QUIC-18, QUIC-27
// =================================== 
public without sharing class qfthankyou {

    // <!-- ===================================
    // # MV Clouds Private Limited
    // # Author: Nimit Shah
    // # Create Date: 18/01/2023
    // # Description: Used to Check and get already created thank you page for the selected form
    // =================================== -->
        @AuraEnabled
        public static Thankyou_Page__c getthankyoupage(Id currentformid){
            try {
                if(currentformid != null){
                    Thankyou_Page__c record = [SELECT Id, Name, Form__c,Thank_you_URL__c, Thankyou_Page_Type__c	, Thankyou_Text__c, ThankYou_Label__c	FROM Thankyou_Page__c WHERE Form__c =: currentformid limit 1];
                    return record;
                }
                return null;
            } catch (Exception e) {
                // error_handler.insert_errordata(e,'qfthankyou','getthankyoupage');
                System.debug(e.getMessage());
                return null;            
            }
        }
    
    
    // <!-- ===================================
    // # MV Clouds Private Limited
    // # Author: Nimit Shah
    // # Create Date: 18/01/2023
    // # Description: Used to Update or insert thank you page 
    // =================================== -->
       @AuraEnabled
   public static string insertrecord(String Name,String picklist, String label, String classtext, String formId, String url, Id currentthankyouid){
        try {
            
            // Thankyou_Page__c tp = [SELECT Id FROM Thankyou_Page__c WHERE Form__c =:formId LIMIT 1];
            // if(tp!=null){

            // }
            // if(String.isNotBlank(classtext)){
                Thankyou_Page__c insertrecord = new Thankyou_Page__c( Name = Name, Form__c = formId, ThankYou_Label__c = label, Thank_you_URL__c = url, Thankyou_Text__c = classtext, Thankyou_Page_Type__c = picklist, Id = currentthankyouid ); 
                Database.upsert(insertrecord);
            // }
            // else{
            //     Thankyou_Page__c insertrecord = new Thankyou_Page__c( Form__c = formId, ThankYou_Label__c = label, Thank_you_URL__c = url, Thankyou_Page_Type__c = picklist, Name = 'Thank you', Id = currentthankyouid );
            //     Database.upsert(insertrecord); 
            // }
            return null;
        } catch (Exception e) {
            System.debug(e.getMessage());
            error_handler.insert_errordata(e,'qfthankyou','insertrecord');
            return null;
        }
       }



       @AuraEnabled
       public static Thankyou_Page__c getrecordslist(Id currentformid){
        try {
            
            if(currentformid != null){
                Thankyou_Page__c Thakyou_form_id = [SELECT Id, Name, Form__c,Thank_you_URL__c, Thankyou_Page_Type__c	, Thankyou_Text__c, ThankYou_Label__c	FROM Thankyou_Page__c WHERE Form__c =: currentformid];
                return Thakyou_form_id;
            }
            else {
                return null;
            }
        } catch (Exception e) {
            // error_handler.insert_errordata(e,'qfthankyou','getrecordslist');
            return null;
        }
       }
    }